name: chat_firebase
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  flutter_svg: ^2.1.0
  cloud_firestore: ^5.6.8
  equatable: ^2.0.7
  injectable: ^2.5.0
  get_it: ^8.0.3
  intl: ^0.20.2
  firebase_messaging: ^15.2.6
  injectable_generator: ^2.7.0
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^19.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13


flutter:
  uses-material-design: true

  assets:
    - assets/general/
    - assets/icons/

flutter_gen:
  output: lib/gen/

  assets:
    enabled: true
    outputs:
      class_name: CAssets
      package_parameter_enabled: false
      style: dot-delimiter
  
  integrations:
      flutter_svg: true
